version: '3.3'

services:
  db:
    image: mysql:8.0.21
    volumes:
      - ./db_data:/var/lib/mysql
      - ./sample_db:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_USER: app_user
      MYSQL_PASSWORD: somepassword
volumes:
  db_data: {}
  sample_db: {}